### ISSUE TITLE
something with i3?!

### ISSUE THREAD

**Issue by hadubrannt** [flags/MacroPad#2]
Hi Luke,
sorry to bother you, but, you know... you asked for it. :)
First of all thank you very much for this, it looks pretty much exactly like what I was looking for. Unfortunately I don't seem to be able to get it to work. 
After my usb numpad has been recognized and the basic conf-file is made, and I run 
`./macropad.py --show ./numpad01.conf`,
the shell shows me this:
```
Traceback (most recent call last):
  File "./macropad.py", line 752, in <module>
    loadConfig(file)
  File "./macropad.py", line 358, in loadConfig
    main(selectedDevice)
  File "./macropad.py", line 706, in main
    i3.subscribe(['window'], focusHandler)
  File "/home/icke/.macropad/MacroPad-master/i3msg.py", line 51, in subscribe
    s.connect(get_i3sockpath())
  File "/home/icke/.macropad/MacroPad-master/i3msg.py", line 16, in get_i3sockpath
    i3sockpath = subprocess.check_output(['i3', '--get-socketpath']).strip()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['i3', '--get-socketpath']' returned non-zero exit status 1.
```
Blindly installing i3 changes the error to 
```
Traceback (most recent call last):
  File "./macropad.py", line 752, in <module>
    loadConfig(file)
  File "./macropad.py", line 358, in loadConfig
    main(selectedDevice)
  File "./macropad.py", line 706, in main
    i3.subscribe(['window'], focusHandler)
  File "/home/icke/.macropad/MacroPad-master/i3msg.py", line 51, in subscribe
    s.connect(get_i3sockpath())
  File "/home/icke/.macropad/MacroPad-master/i3msg.py", line 16, in get_i3sockpath
    i3sockpath = subprocess.check_output(['i3', '--get-socketpath']).strip()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['i3', '--get-socketpath']' returned non-zero exit status 1.
```
I tried it on Debian Buster with KDE and Ubuntu 20.04 with Gnome (both upgraded regularly). I'm happy to send more details, but frankly I have no idea what could be of interest. (I supose you figured this already...)

A hint would be greatly appriciated, cheers from Berlin,
Thorsten

**Comment by flags** [comment]
Hi Thorsten,

You can safely uninstall i3. It's a window manager, which isn't useful to you since you're using KDE and Gnome. MacroPad calls it since there's some i3-specific features for switching macros based on the currently focused window. I've committed a "fix" that I'm unable to test at the moment, but you can try and see if the problem resolves: Pass `--no-i3` to the script alongside the other arguments you're using.

If this doesn't work, delete the `i3msg.py` file. The import will fail and MacroPad should continue. You'll need to replace the file when pulling down new commits, though.

As far as I know, you're the first person to use this besides myself. Please let me know if you encounter any problems. The one thing I do remember being an issue is that the config file can have an incorrect `device` section at the top. If the device isn't recognized, replace `path` with `name`, or the other way around.

**Comment by hadubrannt** [comment]
Morning,
just briefly: the fix doesn't really do what it's supposed to. "too many arguments". I took the liberty to set I3_ENABLED to False manually.
Then: couldn't write to /dev/uinput; ran the script with sudo.
Then: changed PATH to NAME in the conf-file like you said.
Everything seems fine, unfortunately I don't have time to delve into the subtleties of the configuration, right now. 

Thank you again! And even if I am the only one to appreciate your effort, now you can say your software is used internationally. :)
